[2023-04-26 09:16:50,180] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgresoperator_demo.populate_employee_table manual__2023-04-26T09:16:48.022263+00:00 [queued]>
[2023-04-26 09:16:50,185] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgresoperator_demo.populate_employee_table manual__2023-04-26T09:16:48.022263+00:00 [queued]>
[2023-04-26 09:16:50,185] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-26 09:16:50,186] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-26 09:16:50,186] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-26 09:16:50,194] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): populate_employee_table> on 2023-04-26 09:16:48.022263+00:00
[2023-04-26 09:16:50,198] {standard_task_runner.py:52} INFO - Started process 7128 to run task
[2023-04-26 09:16:50,201] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgresoperator_demo', 'populate_employee_table', 'manual__2023-04-26T09:16:48.022263+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/psql_integration.py', '--cfg-path', '/tmp/tmpkx0l79rw', '--error-file', '/tmp/tmpzt7q85ea']
[2023-04-26 09:16:50,201] {standard_task_runner.py:80} INFO - Job 12: Subtask populate_employee_table
[2023-04-26 09:16:50,240] {task_command.py:370} INFO - Running <TaskInstance: postgresoperator_demo.populate_employee_table manual__2023-04-26T09:16:48.022263+00:00 [running]> on host 0d24b0dba33e
[2023-04-26 09:16:50,284] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgresoperator_demo
AIRFLOW_CTX_TASK_ID=populate_employee_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T09:16:48.022263+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T09:16:48.022263+00:00
[2023-04-26 09:16:50,293] {base.py:68} INFO - Using connection ID 'postgres_local' for task execution.
[2023-04-26 09:16:50,297] {dbapi.py:213} INFO - Running statement: -- insert records

INSERT INTO employee
VALUES(1,'Annie','Smith','F', DATE '1988-01-09', 'ani@email.com',5000);

INSERT INTO employee
VALUES(2,'Atul','Singh','M', DATE '2001-01-01', 'atul@email.com',2000);, parameters: None
[2023-04-26 09:16:50,299] {dbapi.py:221} INFO - Rows affected: 1
[2023-04-26 09:16:50,310] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=postgresoperator_demo, task_id=populate_employee_table, execution_date=20230426T091648, start_date=20230426T091650, end_date=20230426T091650
[2023-04-26 09:16:50,334] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-26 09:16:50,358] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
